### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by arunsingh2**
[X] code coverage
[] junit testing

### CODE REVIEW

**Review by arunsingh2 — COMMENTED** [review]
please change reviewer to reviewers

**Review by developerarunsingh2 — COMMENTED** [review]
@arunsingh2 please update serial number also in readme comments

**Comment by arunsingh2** [comment]
> @arunsingh2 please update serial number also in readme comments

updated serial number

**Review by developerarunsingh2 — APPROVED** [review]
@arunsingh2 approved. you can merge pull request now.

**Pull request merged**
